version: '3'
services:
  tomato:
    image: alileza/tomato:latest
    # use the env file for the QUEUE_DSN example
    env_file:
    - queue_dsn.env
    environment:
      APP_BASE_URL: http://sample-app:9000
    volumes:
      - ./tomato.yml:/tomato.yml
      - ./features/:/features/
      - waitfor:/util
    entrypoint: >
      sh -c '/util/waitfor sample-app:9000 && tomato'

  sample-app:
    image: alileza/sample-app:latest
    expose:
      - "9000"
    # use the env file for the QUEUE_DSN example
    env_file:
    - queue_dsn.env
      
    volumes:
      - waitfor:/util
    entrypoint: >
      sh -c '/util/waitfor rabbitmq:5672 && sample-app'

  rabbitmq:
    image: rabbitmq:3.6.1-management
    ports:
        - "5672:5672"

  waitfor:
    image: quay.io/alileza/waitfor:latest
    volumes:
      - waitfor:/bin/
    entrypoint: [ "waitfor", "tomato:9000"]

volumes:
  waitfor: {}
