---

features_path:
  - /features/
resources:
    - name: tomato-psql
      type: postgres
      options:
        datasource: {{ .PSQL_DATASOURCE }}

    - name: tomato-mysql
      type: mysql
      options:
        datasource: {{ .MYSQL_DATASOURCE }}

    - name: tomato-queue
      type: rabbitmq
      options:
        datasource: {{ .RABBITMQ_DATASOURCE }}
        stubs_path: "/stubs"

    - name: tomato-nsq
      type: nsq
      options:
        nsqd: {{ .NSQ_DATASOURCE }}
        stubs_path: "/stubs"

    - name: tomato-wiremock
      type: wiremock
      options:
        base_url: {{ .WIREMOCK_BASE_URL }}

    - name: tomato-http-client
      type: httpclient
      options:
        base_url: {{ .HTTP_CLIENT_BASE_URL }}

    - name: tomato-redis
      type: redis
      options:
        datasource: {{ .REDIS_DATASOURCE }}

    - name: shell-cli
      type: shell

    - name: ls
      type: shell
      options:
        prefix: "ls"
